from alpine
run apk update
run apk add python3 git py3-pip py3-lxml file
run pip3 install --upgrade pip
run pip3 install xmltodict chevron

copy python /cim-codebase-generator/python/
copy cimCodebaseGenerator.py build.py python/templates /cim-codebase-generator/
workdir /cim-codebase-generator
cmd python3 build.py cgmes_v2_4_15 python
